# Generated by Django 2.1.4 on 2018-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_year', models.IntegerField()),
                ('district_name', models.CharField(max_length=100)),
                ('enrollment_grades_k_12', models.IntegerField()),
                ('total_susp', models.IntegerField()),
                ('iss_b', models.IntegerField()),
                ('oss_b', models.IntegerField()),
                ('iss_w', models.IntegerField()),
                ('oss_w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('a_0', models.IntegerField()),
                ('m', models.IntegerField()),
                ('p', models.IntegerField()),
                ('i', models.IntegerField()),
                ('b_disp', models.DecimalField(decimal_places=4, max_digits=5)),
                ('w_disp', models.DecimalField(decimal_places=4, max_digits=5)),
                ('h_disp', models.DecimalField(decimal_places=4, max_digits=5)),
                ('a_disp', models.DecimalField(decimal_places=4, max_digits=5)),
                ('m_disp', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_disp', models.DecimalField(decimal_places=4, max_digits=5)),
                ('i_disp', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
